controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

home:
    path: /
    controller: App\Controller\MainController::home

login:
    path: /api/login
    controller: App\Controller\AuthController::login

stats_posts:
    path: /api/stats/posts
    controller: App\Controller\StatsController::posts

stats_comments:
    path: /api/stats/comments
    controller: App\Controller\StatsController::comments

stats_users:
    path: /api/stats/users
    controller: App\Controller\StatsController::users

stats_nointerraction:
    path: /api/stats/nointerraction
    controller: App\Controller\StatsController::nointerraction

table:
    path: /api/table
    controller: App\Controller\TableController::getTable

logout:
    path: /api/logout
    controller: App\Controller\AuthController::logout